import { Project, User, TaskStatus, ProjectStatus } from './types';

export const MOCK_USER: User = {
  id: 'user-1',
  name: 'Alex Schmidt',
  avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
};

export const MOCK_USER_2: User = {
  id: 'user-2',
  name: 'Julia Weber',
  avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026705d',
};


export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: '25-29 Somersby - Parookaville',
    icon: '🌳',
    taskLists: [],
    status: ProjectStatus.Planned,
    startDate: '2024-07-25',
    endDate: '2024-07-29',
    budgetHours: 120,
    members: [MOCK_USER],
    timeEntries: [],
  },
  {
    id: 'proj-2',
    name: '25-30 B&S 10JAHRE-EVENT 25',
    icon: '🎉',
    taskLists: [],
    status: ProjectStatus.Planned,
    startDate: '2024-07-25',
    endDate: '2024-07-30',
    budgetHours: 200,
    members: [MOCK_USER, MOCK_USER_2],
    timeEntries: [],
  },
  {
    id: 'proj-3',
    name: 'AARON',
    icon: '📁',
    status: ProjectStatus.Active,
    startDate: '2024-07-01',
    endDate: '2024-09-30',
    budgetHours: 400,
    members: [MOCK_USER, MOCK_USER_2],
    timeEntries: [],
    taskLists: [
      {
        id: 'list-1',
        title: 'Kunst, Spaß & Experimente',
        tasks: [
          {
            id: 'task-1',
            title: 'app: Colorizer',
            description: 'Eine App entwickeln, mit der Benutzer Bilder basierend auf KI-Vorschlägen neu einfärben können.',
            status: TaskStatus.InProgress,
            assignee: MOCK_USER,
            timeTrackedSeconds: 40000,
            timeBudgetHours: 86,
            dueDate: '2024-08-15',
            billable: true,
            activity: [
                {id: 'act-1', user: MOCK_USER, text: 'hat die Aufgabe erstellt.', timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString()},
                {id: 'act-2', user: MOCK_USER_2, text: 'wurde zugewiesen.', timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString()},
                {id: 'act-3', user: MOCK_USER, text: 'hat den Status von "TODO" zu "IN_PROGRESS" geändert.', timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString()},
            ],
            subtasks: [
              { 
                id: 'sub-1', 
                title: 'Design-Mockups erstellen', 
                description: '',
                status: TaskStatus.Todo,
                assignee: MOCK_USER,
                timeTrackedSeconds: 3660,
                timeBudgetHours: 8,
                dueDate: '2024-08-10',
                billable: true,
                activity: [],
                todos: [
                  { id: 'sub-todo-1', text: 'Farbpalette definieren', completed: true },
                  { id: 'sub-todo-2', text: 'Wireframes zeichnen', completed: false },
                ]
              },
            ],
            todos: [
              { id: 'todo-1', text: 'Eintrag hinzufügen', completed: false },
              { id: 'todo-2', text: 'UI-Mockup überprüfen', completed: true },
            ],
          },
          {
            id: 'task-2',
            title: 'App erklären',
            description: '',
            status: TaskStatus.Todo,
            assignee: MOCK_USER,
            timeTrackedSeconds: 0,
            timeBudgetHours: null,
            dueDate: null,
            billable: true,
            subtasks: [],
            todos: [],
            activity: [],
          },
          {
            id: 'task-3',
            title: 'App: jaa.coolMediaControll (MC)',
            description: '',
            status: TaskStatus.Todo,
            assignee: MOCK_USER,
            timeTrackedSeconds: 300000,
            timeBudgetHours: null,
            dueDate: '2024-08-20',
            billable: true,
            subtasks: [],
            todos: [],
            activity: [],
          },
          {
            id: 'task-4',
            title: 'Flux - Studio Lighting',
            description: '',
            status: TaskStatus.Todo,
            assignee: MOCK_USER,
            timeTrackedSeconds: 8460,
            timeBudgetHours: null,
            dueDate: '2024-08-18',
            billable: true,
            subtasks: [],
            todos: [],
            activity: [],
          },
        ],
      },
      {
        id: 'list-2',
        title: 'Sonstiges',
        tasks: [
          {
            id: 'task-5',
            title: 'sonstig',
            description: '',
            status: TaskStatus.Todo,
            assignee: MOCK_USER,
            timeTrackedSeconds: 9,
            timeBudgetHours: 28,
            dueDate: null,
            billable: true,
            subtasks: [],
            todos: [],
            activity: [],
          },
          {
            id: 'task-6',
            title: 'Privat',
            description: '',
            status: TaskStatus.Todo,
            assignee: MOCK_USER,
            timeTrackedSeconds: 43680,
            timeBudgetHours: null,
            dueDate: null,
            billable: true,
            subtasks: [],
            todos: [],
            activity: [],
          },
        ],
      },
    ],
  },
  {
    id: 'proj-4',
    name: 'jaa.cool INSTAGRAM',
    icon: '📸',
    taskLists: [],
    status: ProjectStatus.Active,
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    budgetHours: 50,
    members: [MOCK_USER_2],
    timeEntries: [],
  },
  {
    id: 'proj-5',
    name: 'jaa.cool INTERN (Geschäftsführung)',
    icon: '💼',
    taskLists: [],
    status: ProjectStatus.Active,
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    budgetHours: 1000,
    members: [MOCK_USER],
    timeEntries: [],
  },
];