import { Project, User, TaskStatus, ProjectStatus, UserStatus, Gender, Role, PermissionStatus, AbsenceRequest, AbsenceType, AbsenceStatus } from './types';

export const MOCK_USER: User = {
  id: 'user-1',
  name: 'AARON',
  firstName: 'Aaron',
  lastName: 'Schmidt',
  title: 'Creative Dire...',
  email: 'aaron@jaa.cool',
  avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
  teams: ['Creative Dire...', 'AARON'],
  tags: ['editor', '+2'],
  status: UserStatus.Active,
  role: 'role-1', // Admin
  gender: Gender.Male,
  position: 'Creative Director',
  birthday: '1990-01-01',
  password: 'password123',
};

export const MOCK_USER_2: User = {
  id: 'user-2',
  name: 'Han',
  firstName: 'Han',
  lastName: 'Solo',
  email: 'han@jaa.cool',
  avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026705d',
  tags: ['editor'],
  status: UserStatus.Active,
  role: 'role-3', // Editor
  gender: Gender.Male,
  position: 'Smuggler',
  birthday: '1980-05-25',
  password: 'password123',
};

export const ADMIN_USER: User = {
  id: 'user-admin',
  name: 'admin',
  firstName: 'Admin',
  lastName: 'User',
  email: 'admin@example.com',
  avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026706d',
  status: UserStatus.Active,
  role: 'role-1', // Admin
  gender: Gender.Diverse,
  position: 'Administrator',
  birthday: '2000-01-01',
  password: '12345',
};

export const MOCK_USERS: User[] = [
  MOCK_USER,
  MOCK_USER_2,
  {
    id: 'user-3',
    name: 'JAKOB',
    title: 'Executive Pro...',
    email: 'jakob@jaa.cool',
    avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026707d',
    tags: ['editor', '+2'],
    status: UserStatus.Active,
    role: 'role-3', // Editor
  },
  {
    id: 'user-4',
    name: 'Maresa',
    email: 'maresa@jaa.cool',
    avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026708d',
    tags: ['Produktion'],
    status: UserStatus.Inactive,
    role: 'role-5', // Produzent:in
  },
  {
    id: 'user-5',
    name: 'Nastja',
    email: 'nastja@jaa.cool',
    avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026709d',
    tags: ['editor'],
    status: UserStatus.Inactive,
    role: 'role-4', // Nutzer
  },
  {
    id: 'user-6',
    name: 'Tiffany',
    title: 'Produzentin',
    email: 'tiffany@jaa.cool',
    avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026710d',
    tags: ['Produktion'],
    status: UserStatus.Active,
    role: 'role-5', // Produzent:in
  },
  {
    id: 'user-7',
    name: 'TOBI',
    email: 'tobi@jaa.cool',
    avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026711d',
    tags: ['editor'],
    status: UserStatus.Inactive,
    role: 'role-3', // Editor
  },
];

export const MOCK_ROLES: Role[] = [
  {
    id: 'role-1',
    name: 'Admin',
    permissions: [
      { name: 'Projekte', status: PermissionStatus.Granted },
      { name: 'User', status: PermissionStatus.Granted },
      { name: 'Kunden', status: PermissionStatus.Granted },
      { name: 'Einstellungen', status: PermissionStatus.Granted },
      { name: 'Zeit bearbeiten', status: PermissionStatus.Granted },
    ],
  },
  {
    id: 'role-2',
    name: 'Gast',
    permissions: [
      { name: 'Projekte', status: PermissionStatus.Denied },
      { name: 'User', status: PermissionStatus.Denied },
      { name: 'Kunden', status: PermissionStatus.Denied },
      { name: 'Einstellungen', status: PermissionStatus.Denied },
      { name: 'Zeit bearbeiten', status: PermissionStatus.Denied },
    ],
  },
  {
    id: 'role-3',
    name: 'Editor',
    permissions: [
      { name: 'Projekte', status: PermissionStatus.Denied },
      { name: 'User', status: PermissionStatus.Denied },
      { name: 'Kunden', status: PermissionStatus.Denied },
      { name: 'Einstellungen', status: PermissionStatus.Partial },
      { name: 'Zeit bearbeiten', status: PermissionStatus.Denied },
    ],
  },
  {
    id: 'role-4',
    name: 'Nutzer',
    permissions: [
      { name: 'Projekte', status: PermissionStatus.Partial },
      { name: 'User', status: PermissionStatus.Partial },
      { name: 'Kunden', status: PermissionStatus.Granted },
      { name: 'Einstellungen', status: PermissionStatus.Partial },
      { name: 'Zeit bearbeiten', status: PermissionStatus.Granted },
    ],
  },
  {
    id: 'role-5',
    name: 'Produzent:in',
    permissions: [
      { name: 'Projekte', status: PermissionStatus.Partial },
      { name: 'User', status: PermissionStatus.Partial },
      { name: 'Kunden', status: PermissionStatus.Granted },
      { name: 'Einstellungen', status: PermissionStatus.Denied },
      { name: 'Zeit bearbeiten', status: PermissionStatus.Granted },
    ],
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: '25-29 Somersby - Parookaville',
    icon: '🌳',
    taskLists: [],
    status: ProjectStatus.Planned,
    startDate: '2024-07-25',
    endDate: '2024-07-29',
    budgetHours: 120,
    members: [MOCK_USER],
  },
  {
    id: 'proj-2',
    name: '25-30 B&S 10JAHRE-EVENT 25',
    icon: '🎉',
    taskLists: [],
    status: ProjectStatus.Planned,
    startDate: '2024-07-25',
    endDate: '2024-07-30',
    budgetHours: 200,
    members: [MOCK_USER, MOCK_USER_2],
  },
  {
    id: 'proj-3',
    name: 'AARON',
    icon: '📁',
    status: ProjectStatus.Active,
    startDate: '2024-07-01',
    endDate: '2024-09-30',
    budgetHours: 400,
    members: [MOCK_USER, MOCK_USER_2],
    taskLists: [
      {
        id: 'list-1',
        title: 'Kunst, Spaß & Experimente',
        tasks: [
          {
            id: 'task-1',
            title: 'app: Colorizer',
            description: 'Eine App entwickeln, mit der Benutzer Bilder basierend auf KI-Vorschlägen neu einfärben können.',
            status: TaskStatus.InProgress,
            assignees: [MOCK_USER],
            timeTrackedSeconds: 40000,
            timeBudgetHours: 86,
            dueDate: '2024-08-15',
            billable: true,
            activity: [
                {id: 'act-1', user: MOCK_USER, text: 'hat die Aufgabe erstellt.', timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString()},
                {id: 'act-2', user: MOCK_USER_2, text: 'wurde zugewiesen.', timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString()},
                {id: 'act-3', user: MOCK_USER, text: 'hat den Status von "TODO" zu "IN_PROGRESS" geändert.', timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString()},
            ],
            subtasks: [
              { 
                id: 'sub-1', 
                title: 'Design-Mockups erstellen', 
                description: '',
                status: TaskStatus.Todo,
                assignees: [MOCK_USER],
                timeTrackedSeconds: 3660,
                timeBudgetHours: 8,
                dueDate: '2024-08-10',
                billable: true,
                activity: [],
                todos: [
                  { id: 'sub-todo-1', text: 'Farbpalette definieren', completed: true },
                  { id: 'sub-todo-2', text: 'Wireframes zeichnen', completed: false },
                ]
              },
            ],
            todos: [
              { id: 'todo-1', text: 'Eintrag hinzufügen', completed: false },
              { id: 'todo-2', text: 'UI-Mockup überprüfen', completed: true },
            ],
          },
          {
            id: 'task-2',
            title: 'App erklären',
            description: '',
            status: TaskStatus.Todo,
            assignees: [MOCK_USER],
            timeTrackedSeconds: 0,
            timeBudgetHours: null,
            dueDate: null,
            billable: true,
            subtasks: [],
            todos: [],
            activity: [],
          },
          {
            id: 'task-3',
            title: 'App: jaa.coolMediaControll (MC)',
            description: '',
            status: TaskStatus.Todo,
            assignees: [MOCK_USER],
            timeTrackedSeconds: 300000,
            timeBudgetHours: null,
            dueDate: '2024-08-20',
            billable: true,
            subtasks: [],
            todos: [],
            activity: [],
          },
          {
            id: 'task-4',
            title: 'Flux - Studio Lighting',
            description: '',
            status: TaskStatus.Todo,
            assignees: [MOCK_USER],
            timeTrackedSeconds: 8460,
            timeBudgetHours: null,
            dueDate: '2024-08-18',
            billable: true,
            subtasks: [],
            todos: [],
            activity: [],
          },
        ],
      },
      {
        id: 'list-2',
        title: 'Sonstiges',
        tasks: [
          {
            id: 'task-5',
            title: 'sonstig',
            description: '',
            status: TaskStatus.Todo,
            assignees: [MOCK_USER],
            timeTrackedSeconds: 9,
            timeBudgetHours: 28,
            dueDate: null,
            billable: true,
            subtasks: [],
            todos: [],
            activity: [],
          },
          {
            id: 'task-6',
            title: 'Privat',
            description: '',
            status: TaskStatus.Todo,
            assignees: [MOCK_USER],
            timeTrackedSeconds: 43680,
            timeBudgetHours: null,
            dueDate: null,
            billable: true,
            subtasks: [],
            todos: [],
            activity: [],
          },
        ],
      },
    ],
  },
  {
    id: 'proj-4',
    name: 'jaa.cool INSTAGRAM',
    icon: '📸',
    taskLists: [],
    status: ProjectStatus.Active,
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    budgetHours: 50,
    members: [MOCK_USER_2],
  },
  {
    id: 'proj-5',
    name: 'jaa.cool INTERN (Geschäftsführung)',
    icon: '💼',
    taskLists: [],
    status: ProjectStatus.Active,
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    budgetHours: 1000,
    members: [MOCK_USER],
  },
];

// Mock Absence Requests
export const MOCK_ABSENCE_REQUESTS: AbsenceRequest[] = [
  {
    id: 'absence-1',
    user: MOCK_USER,
    type: AbsenceType.Vacation,
    startDate: '2025-11-20',
    endDate: '2025-11-22',
    status: AbsenceStatus.Pending,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'absence-2',
    user: MOCK_USER_2,
    type: AbsenceType.Sick,
    startDate: '2025-11-18',
    endDate: '2025-11-18',
    halfDay: 'morning',
    status: AbsenceStatus.Approved,
    approvedBy: ADMIN_USER,
    approvedAt: new Date().toISOString(),
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'absence-3',
    user: MOCK_USER,
    type: AbsenceType.HomeOffice,
    startDate: '2025-11-25',
    endDate: '2025-11-25',
    status: AbsenceStatus.Approved,
    approvedBy: ADMIN_USER,
    approvedAt: new Date().toISOString(),
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];